use super::{RuntimeRole, runtime_role_wallet_registered, runtime_role_wallet_registration};
use crate::{
    NetworkEventIngest, NodeRuntimeState, RpcHttpServer, TensorVmLibp2pService,
    types::{Address, Hash},
};

pub struct RuntimeStatusSnapshot {
    pub(super) served_requests: usize,
    pub(super) produced_blocks: usize,
    pub(super) network_applied_blocks: usize,
    pub(super) local_synthetic_job_producer: bool,
    pub(super) local_block_proposer: bool,
    pub(super) local_block_proposer_delay_blocks: u64,
    pub(super) local_block_proposer_delay_satisfied: bool,
    pub(super) proposer_cooldown_blocks: u64,
    pub(super) proposer_cadence_ready: bool,
    pub(super) proposer_cadence_remaining_blocks: u64,
    pub(super) proposer_challenge_throttle_ready: bool,
    pub(super) latest_height: u64,
    pub(super) p2p_connected_peers: usize,
    pub(super) p2p_observed_blocks: usize,
    pub(super) p2p_observed_block_payloads: usize,
    pub(super) p2p_observed_block_votes: usize,
    pub(super) p2p_observed_jobs: usize,
    pub(super) p2p_observed_receipts: usize,
    pub(super) p2p_observed_attestations: usize,
    pub(super) p2p_latest_observed_block_height: u64,
    pub(super) p2p_latest_observed_block_hash: [u8; 32],
    pub(super) p2p_observed_block_hashes: Vec<[u8; 32]>,
    pub(super) p2p_latest_observed_block_payload_height: u64,
    pub(super) p2p_latest_observed_block_payload_hash: [u8; 32],
    pub(super) p2p_observed_block_payload_hashes: Vec<[u8; 32]>,
    pub(super) network_events: NetworkEventIngest,
    pub(super) role_wallet_address: Option<Address>,
    pub(super) role_wallet_registration: &'static str,
    pub(super) role_wallet_registered: bool,
    pub(super) miner_work_ready: bool,
    pub(super) miner_assigned_jobs_seen: usize,
    pub(super) miner_unreceipted_jobs: usize,
    pub(super) miner_receipts_submitted: usize,
    pub(super) miner_tensors_inserted: usize,
    pub(super) miner_trace_bisection_rounds_submitted: usize,
    pub(super) validator_work_ready: bool,
    pub(super) validator_assigned_receipts_seen: usize,
    pub(super) validator_unattested_receipts: usize,
    pub(super) validator_artifact_ready_receipts: usize,
    pub(super) validator_artifact_missing_receipts: usize,
    pub(super) validator_remote_tensor_fetch_attempts: usize,
    pub(super) validator_remote_tensor_fetch_successes: usize,
    pub(super) validator_remote_tensor_fetch_failures: usize,
    pub(super) validator_remote_tensor_fetch_bytes: usize,
    pub(super) validator_remote_tensors_inserted: usize,
    pub(super) randomness_beacons_observed: usize,
    pub(super) randomness_beacons_applied: usize,
    pub(super) randomness_beacons_skipped: usize,
    pub(super) randomness_beacon_failures: usize,
    pub(super) randomness_latest_source_id: String,
    pub(super) randomness_latest_round: u64,
    pub(super) randomness_last_error: String,
    pub(super) randomness_public_drand_fetch_attempts: usize,
    pub(super) randomness_public_drand_fetch_successes: usize,
    pub(super) randomness_public_drand_fetch_stale: usize,
    pub(super) randomness_public_drand_consecutive_failures: usize,
    pub(super) randomness_public_drand_backoff_remaining_ticks: u64,
    pub(super) randomness_public_drand_expected_latest_round: u64,
    pub(super) randomness_public_drand_fetched_round_lag: u64,
    pub(super) randomness_public_drand_max_round_lag: u64,
    pub(super) randomness_public_drand_rounds_per_chain_epoch: u64,
    pub(super) randomness_public_drand_chain_epoch: u64,
    pub(super) randomness_public_drand_fresh: bool,
    pub(super) validator_attestations_submitted: usize,
    pub(super) validator_audit_work_ready: bool,
    pub(super) validator_assigned_audits_seen: usize,
    pub(super) validator_unreported_audits: usize,
    pub(super) validator_audit_artifact_ready: usize,
    pub(super) validator_audit_artifact_missing: usize,
    pub(super) validator_audit_reports_submitted: usize,
    pub(super) validator_vrf_key_registered: bool,
    pub(super) validator_vrf_key_registration_count: usize,
    pub(super) validator_vrf_key_public_key: Hash,
    pub(super) validator_proposer_work_ready: bool,
    pub(super) validator_proposer_settled_receipts_seen: usize,
    pub(super) validator_proposer_artifact_ready_receipts_seen: usize,
    pub(super) validator_proposer_attested_receipts_seen: usize,
    pub(super) validator_blocks_proposed: usize,
    pub(super) validator_useful_blocks_proposed: usize,
    pub(super) validator_fallback_blocks_proposed: usize,
    pub(super) validator_receipts_proposed: usize,
    pub(super) validator_block_votes_submitted: usize,
    pub(super) validator_trace_bisection_opens_submitted: usize,
}

impl RuntimeStatusSnapshot {
    pub fn from_runtime_state(
        state: &NodeRuntimeState,
        server: &RpcHttpServer,
        p2p_service: &TensorVmLibp2pService,
        local_synthetic_job_producer: bool,
        local_block_proposer: bool,
        local_block_proposer_delay_blocks: u64,
        local_block_proposer_delay_satisfied: bool,
        role: RuntimeRole,
        role_wallet_address: Option<Address>,
    ) -> Self {
        let chain = &server.gateway().node.chain;
        Self {
            served_requests: state.served_requests(),
            produced_blocks: state.produced_blocks(),
            network_applied_blocks: state.network_applied_blocks(),
            local_synthetic_job_producer,
            local_block_proposer,
            local_block_proposer_delay_blocks,
            local_block_proposer_delay_satisfied,
            proposer_cooldown_blocks: chain.params().proposer_cooldown_blocks,
            proposer_cadence_ready: match role_wallet_address {
                Some(address) => chain.proposer_cadence_ready(address),
                None => true,
            },
            proposer_cadence_remaining_blocks: match role_wallet_address {
                Some(address) => chain.proposer_cadence_remaining_blocks(address),
                None => 0,
            },
            proposer_challenge_throttle_ready: match role_wallet_address {
                Some(address) => chain.proposer_challenge_throttle_ready(address),
                None => true,
            },
            latest_height: server.gateway().node.chain.state().height(),
            p2p_connected_peers: p2p_service.connected_peer_count(),
            p2p_observed_blocks: p2p_service.observed_block_gossip_count(),
            p2p_observed_block_payloads: p2p_service.observed_block_payload_gossip_count(),
            p2p_observed_block_votes: p2p_service.observed_block_vote_gossip_count(),
            p2p_observed_jobs: p2p_service.observed_job_gossip_count(),
            p2p_observed_receipts: p2p_service.observed_receipt_gossip_count(),
            p2p_observed_attestations: p2p_service.observed_attestation_gossip_count(),
            p2p_latest_observed_block_height: p2p_service.latest_observed_block_height(),
            p2p_latest_observed_block_hash: p2p_service.latest_observed_block_hash(),
            p2p_observed_block_hashes: p2p_service.observed_block_hashes(),
            p2p_latest_observed_block_payload_height: p2p_service
                .latest_observed_block_payload_height(),
            p2p_latest_observed_block_payload_hash: p2p_service
                .latest_observed_block_payload_hash(),
            p2p_observed_block_payload_hashes: p2p_service.observed_block_payload_hashes(),
            network_events: state.network_events(),
            role_wallet_address,
            role_wallet_registration: runtime_role_wallet_registration(
                role,
                role_wallet_address,
                chain,
            ),
            role_wallet_registered: runtime_role_wallet_registered(
                role,
                role_wallet_address,
                chain,
            ),
            miner_work_ready: state.miner_work_ready(),
            miner_assigned_jobs_seen: state.miner_assigned_jobs_seen(),
            miner_unreceipted_jobs: state.miner_unreceipted_jobs(),
            miner_receipts_submitted: state.miner_receipts_submitted(),
            miner_tensors_inserted: state.miner_tensors_inserted(),
            miner_trace_bisection_rounds_submitted: state.miner_trace_bisection_rounds_submitted(),
            validator_work_ready: state.validator_work_ready(),
            validator_assigned_receipts_seen: state.validator_assigned_receipts_seen(),
            validator_unattested_receipts: state.validator_unattested_receipts(),
            validator_artifact_ready_receipts: state.validator_artifact_ready_receipts(),
            validator_artifact_missing_receipts: state.validator_artifact_missing_receipts(),
            validator_remote_tensor_fetch_attempts: state.validator_remote_tensor_fetch_attempts(),
            validator_remote_tensor_fetch_successes: state
                .validator_remote_tensor_fetch_successes(),
            validator_remote_tensor_fetch_failures: state.validator_remote_tensor_fetch_failures(),
            validator_remote_tensor_fetch_bytes: state.validator_remote_tensor_fetch_bytes(),
            validator_remote_tensors_inserted: state.validator_remote_tensors_inserted(),
            randomness_beacons_observed: state.randomness_beacons_observed(),
            randomness_beacons_applied: state.randomness_beacons_applied(),
            randomness_beacons_skipped: state.randomness_beacons_skipped(),
            randomness_beacon_failures: state.randomness_beacon_failures(),
            randomness_latest_source_id: state.randomness_latest_source_id().to_owned(),
            randomness_latest_round: state.randomness_latest_round(),
            randomness_last_error: state.randomness_last_error().to_owned(),
            randomness_public_drand_fetch_attempts: state.randomness_public_drand_fetch_attempts(),
            randomness_public_drand_fetch_successes: state
                .randomness_public_drand_fetch_successes(),
            randomness_public_drand_fetch_stale: state.randomness_public_drand_fetch_stale(),
            randomness_public_drand_consecutive_failures: state
                .randomness_public_drand_consecutive_failures(),
            randomness_public_drand_backoff_remaining_ticks: state
                .randomness_public_drand_backoff_remaining_ticks(),
            randomness_public_drand_expected_latest_round: state
                .randomness_public_drand_expected_latest_round(),
            randomness_public_drand_fetched_round_lag: state
                .randomness_public_drand_fetched_round_lag(),
            randomness_public_drand_max_round_lag: state.randomness_public_drand_max_round_lag(),
            randomness_public_drand_rounds_per_chain_epoch: state
                .randomness_public_drand_rounds_per_chain_epoch(),
            randomness_public_drand_chain_epoch: state.randomness_public_drand_chain_epoch(),
            randomness_public_drand_fresh: state.randomness_public_drand_fresh(),
            validator_attestations_submitted: state.validator_attestations_submitted(),
            validator_audit_work_ready: state.validator_audit_work_ready(),
            validator_assigned_audits_seen: state.validator_assigned_audits_seen(),
            validator_unreported_audits: state.validator_unreported_audits(),
            validator_audit_artifact_ready: state.validator_audit_artifact_ready(),
            validator_audit_artifact_missing: state.validator_audit_artifact_missing(),
            validator_audit_reports_submitted: state.validator_audit_reports_submitted(),
            validator_vrf_key_registered: state.validator_vrf_key_registered(),
            validator_vrf_key_registration_count: state.validator_vrf_key_registration_count(),
            validator_vrf_key_public_key: state.validator_vrf_key_public_key(),
            validator_proposer_work_ready: state.validator_proposer_work_ready(),
            validator_proposer_settled_receipts_seen: state
                .validator_proposer_settled_receipts_seen(),
            validator_proposer_artifact_ready_receipts_seen: state
                .validator_proposer_artifact_ready_receipts_seen(),
            validator_proposer_attested_receipts_seen: state
                .validator_proposer_attested_receipts_seen(),
            validator_blocks_proposed: state.validator_blocks_proposed(),
            validator_useful_blocks_proposed: state.validator_useful_blocks_proposed(),
            validator_fallback_blocks_proposed: state.validator_fallback_blocks_proposed(),
            validator_receipts_proposed: state.validator_receipts_proposed(),
            validator_block_votes_submitted: state.validator_block_votes_submitted(),
            validator_trace_bisection_opens_submitted: state
                .validator_trace_bisection_opens_submitted(),
        }
    }
}

pub struct RuntimeP2pReport<'a> {
    pub peer_id: &'a str,
    pub topics: usize,
    pub request_response_protocols: usize,
    pub bootstrap_peer_count: usize,
    pub identity: &'a str,
    pub max_transmit_bytes: usize,
    pub request_timeout_seconds: u64,
    pub max_concurrent_streams: usize,
    pub idle_timeout_seconds: u64,
}
